'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, ClipboardList, Download, FolderPlus, Globe2, LogIn, LogOut, Plus, Users } from 'lucide-react';
import * as XLSX from 'xlsx';
import { supabase } from '@/lib/supabase';

type Lang = 'id' | 'en';
type Profile = { id: string; full_name: string; role: 'admin' | 'user' };
type Project = { id: string; project_code: string; name: string; description: string };
type Completion = { project_id: string; user_id: string; completed_on: string; profiles?: { full_name: string }; projects?: { name: string; project_code: string } };

const text = {
  id: { app:'Pelacak Proyek', login:'Masuk', email:'Email', password:'Kata sandi', signIn:'Masuk', signUp:'Buat akun', logout:'Keluar', projects:'Proyek Saya', admin:'Admin', welcome:'Selamat datang', available:'Proyek tersedia', completed:'Selesai', noProjects:'Belum ada proyek yang tersedia.', finish:'Selesaikan', selectDate:'Pilih tanggal selesai', dateNote:'Tanggal hanya dapat dipilih dari 30 hari terakhir sampai hari ini.', cancel:'Batal', save:'Simpan', overview:'Ringkasan', totalProjects:'Total proyek', totalUsers:'Total pengguna', completions:'Proyek selesai', createProject:'Buat proyek', projectName:'Nama proyek', projectId:'ID proyek', description:'Deskripsi', assignTo:'Tugaskan ke', allUsers:'Semua pengguna (default)', create:'Buat proyek', records:'Rekapan penyelesaian', export:'Ekspor Excel', search:'Cari nama atau proyek…', user:'Nama', date:'Tanggal selesai', createAccount:'Buat akun baru', name:'Nama lengkap', authHint:'Gunakan email dan kata sandi untuk melanjutkan.', loading:'Memuat…', setup:'Tambahkan variabel Supabase terlebih dahulu.' },
  en: { app:'Project Tracker', login:'Sign in', email:'Email', password:'Password', signIn:'Sign in', signUp:'Create account', logout:'Sign out', projects:'My Projects', admin:'Admin', welcome:'Welcome', available:'Available projects', completed:'Completed', noProjects:'There are no available projects yet.', finish:'Complete', selectDate:'Select completion date', dateNote:'You can select a date from the last 30 days through today.', cancel:'Cancel', save:'Save', overview:'Overview', totalProjects:'Total projects', totalUsers:'Total users', completions:'Completed projects', createProject:'Create project', projectName:'Project name', projectId:'Project ID', description:'Description', assignTo:'Assign to', allUsers:'All users (default)', create:'Create project', records:'Completion records', export:'Export Excel', search:'Search name or project…', user:'Name', date:'Completion date', createAccount:'Create a new account', name:'Full name', authHint:'Use your email and password to continue.', loading:'Loading…', setup:'Add your Supabase environment variables first.' }
} as const;

function today() { return new Date().toISOString().slice(0, 10); }
function minDate() { const date = new Date(); date.setDate(date.getDate() - 30); return date.toISOString().slice(0, 10); }

export default function Home() {
  const [lang, setLang] = useState<Lang>('id'); const t = text[lang];
  const [profile, setProfile] = useState<Profile | null>(null); const [projects, setProjects] = useState<Project[]>([]); const [completions, setCompletions] = useState<Completion[]>([]); const [users, setUsers] = useState<Profile[]>([]);
  const [loading, setLoading] = useState(true); const [authMode, setAuthMode] = useState<'in'|'up'>('in'); const [finishProject, setFinishProject] = useState<Project | null>(null); const [createOpen, setCreateOpen] = useState(false); const [query, setQuery] = useState('');
  const configured = Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
  async function load() {
    if (!configured) return setLoading(false); const { data: { user } } = await supabase.auth.getUser();
    if (!user) { setProfile(null); setLoading(false); return; }
    const { data: own } = await supabase.from('profiles').select('id,full_name,role').eq('id', user.id).single();
    if (!own) return setLoading(false); setProfile(own as Profile);
    const [{ data: allProjects }, { data: assignments }, { data: done }, { data: allUsers }] = await Promise.all([
      supabase.from('projects').select('id,project_code,name,description').order('created_at', { ascending:false }),
      own.role === 'admin' ? Promise.resolve({ data: [] }) : supabase.from('project_assignments').select('project_id'),
      supabase.from('project_completions').select('project_id,user_id,completed_on,profiles(full_name),projects(name,project_code)').order('completed_on', { ascending:false }),
      own.role === 'admin' ? supabase.from('profiles').select('id,full_name,role').order('full_name') : Promise.resolve({ data: [] })
    ]);
    const visibleIds = new Set((assignments || []).map((a: { project_id: string }) => a.project_id));
    const normalizedCompletions = (done || []).map((row: any) => ({ ...row, profiles: Array.isArray(row.profiles) ? row.profiles[0] : row.profiles, projects: Array.isArray(row.projects) ? row.projects[0] : row.projects }));
    setProjects((own.role === 'admin' ? allProjects || [] : (allProjects || []).filter((p: Project) => visibleIds.has(p.id))) as Project[]); setCompletions(normalizedCompletions as Completion[]); setUsers((allUsers || []) as Profile[]); setLoading(false);
  }
  useEffect(() => { load(); const { data } = supabase.auth.onAuthStateChange(() => load()); return () => data.subscription.unsubscribe(); }, []);
  async function authenticate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const email = String(form.get('email')); const password = String(form.get('password')); const full_name = String(form.get('full_name') || ''); const result = authMode === 'in' ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password, options:{ data:{ full_name } } }); if (result.error) alert(result.error.message); else if (authMode === 'up') alert(lang === 'id' ? 'Akun dibuat. Periksa email untuk verifikasi bila diminta.' : 'Account created. Check your email if verification is required.'); }
  async function complete(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!profile || !finishProject) return; const completed_on = String(new FormData(event.currentTarget).get('completed_on')); const { error } = await supabase.from('project_completions').upsert({ project_id:finishProject.id, user_id:profile.id, completed_on }, { onConflict:'project_id,user_id' }); if (error) alert(error.message); else { setFinishProject(null); load(); } }
  async function createProject(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!profile) return; const f = new FormData(event.currentTarget); const { data, error } = await supabase.from('projects').insert({ name:f.get('name'), project_code:f.get('code'), description:f.get('description'), created_by:profile.id }).select().single(); if (error || !data) return alert(error?.message); const target = String(f.get('user_id') || ''); const assigned = await supabase.from('project_assignments').insert({ project_id:data.id, assigned_to: target || null }); if (assigned.error) return alert(assigned.error.message); setCreateOpen(false); load(); }
  const doneIds = useMemo(() => new Set(completions.filter(c => c.user_id === profile?.id).map(c => c.project_id)), [completions, profile]);
  const records = completions.filter(c => `${c.profiles?.full_name} ${c.projects?.name} ${c.projects?.project_code}`.toLowerCase().includes(query.toLowerCase()));
  function exportExcel() { const rows = records.map(r => ({ [t.user]:r.profiles?.full_name || '', [t.projectName]:r.projects?.name || '', [t.projectId]:r.projects?.project_code || '', [t.date]:r.completed_on })); const sheet = XLSX.utils.json_to_sheet(rows); const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, sheet, t.records); XLSX.writeFile(book, `rekapan-proyek-${today()}.xlsx`); }
  if (!configured) return <main className="shell"><div className="notice">{t.setup}</div></main>;
  if (loading) return <main className="shell"><p>{t.loading}</p></main>;
  if (!profile) return <Auth lang={lang} setLang={setLang} t={t} mode={authMode} setMode={setAuthMode} onSubmit={authenticate} />;
  const isAdmin = profile.role === 'admin';
  return <main className="shell"><header className="topbar"><div className="brand"><span className="brand-mark"><ClipboardList size={21}/></span>{t.app}</div><div className="top-actions"><button className="lang" onClick={() => setLang(lang === 'id' ? 'en':'id')}><Globe2 size={15}/> {lang === 'id' ? 'EN' : 'ID'}</button><button className="icon-button" onClick={() => supabase.auth.signOut()}><LogOut size={16}/>{t.logout}</button></div></header><nav className="nav"><a className="active">{isAdmin ? t.admin : t.projects}</a></nav>{isAdmin ? <Admin t={t} projects={projects} users={users} records={records} query={query} setQuery={setQuery} onExport={exportExcel} onCreate={() => setCreateOpen(true)} /> : <User t={t} profile={profile} projects={projects} doneIds={doneIds} onFinish={setFinishProject} />}{finishProject && <FinishModal t={t} project={finishProject} onClose={() => setFinishProject(null)} onSubmit={complete}/>} {createOpen && <CreateModal t={t} users={users} onClose={() => setCreateOpen(false)} onSubmit={createProject}/>}</main>;
}

function Auth({lang,setLang,t,mode,setMode,onSubmit}: any) { return <main className="shell" style={{maxWidth:450}}><header className="topbar"><div className="brand"><span className="brand-mark"><ClipboardList size={21}/></span>{t.app}</div><button className="lang" onClick={() => setLang(lang === 'id' ? 'en':'id')}><Globe2 size={15}/> {lang === 'id' ? 'EN':'ID'}</button></header><section className="card"><h1>{mode === 'in' ? t.login : t.createAccount}</h1><p>{t.authHint}</p><form onSubmit={onSubmit}>{mode === 'up' && <div className="field"><label>{t.name}</label><input required name="full_name"/></div>}<div className="field"><label>{t.email}</label><input required name="email" type="email"/></div><div className="field"><label>{t.password}</label><input required name="password" type="password" minLength={6}/></div><button className="primary" type="submit"><LogIn size={16}/>{mode === 'in' ? t.signIn:t.signUp}</button></form><p className="note"><button className="secondary" onClick={() => setMode(mode === 'in' ? 'up':'in')}>{mode === 'in' ? t.signUp:t.signIn}</button></p></section></main> }
function User({t,profile,projects,doneIds,onFinish}: any) { return <><section className="hero"><div><h1>{t.welcome}, {profile.full_name}</h1><p>{t.available}</p></div></section><section className="projects">{projects.length ? projects.map((p:Project) => <article className="card project" key={p.id}><span className={doneIds.has(p.id) ? 'tag done':'tag'}>{doneIds.has(p.id) ? t.completed:p.project_code}</span><h3>{p.name}</h3><p>{p.description}</p><footer>{doneIds.has(p.id) ? <span className="tag done"><CheckCircle2 size={14}/> {t.completed}</span> : <button className="primary" onClick={() => onFinish(p)}><CheckCircle2 size={16}/>{t.finish}</button>}</footer></article>) : <div className="empty card">{t.noProjects}</div>}</section></> }
function Admin({t,projects,users,records,query,setQuery,onExport,onCreate}: any) { return <><section className="hero"><div><h1>{t.overview}</h1><p>{t.records}</p></div><button className="primary" onClick={onCreate}><FolderPlus size={17}/>{t.createProject}</button></section><section className="grid"><div className="stat"><div className="label">{t.totalProjects}</div><div className="number">{projects.length}</div></div><div className="stat"><div className="label">{t.totalUsers}</div><div className="number">{users.filter((u:Profile)=>u.role==='user').length}</div></div><div className="stat"><div className="label">{t.completions}</div><div className="number">{records.length}</div></div></section><section className="card"><div className="toolbar"><h2>{t.records}</h2><button className="secondary" onClick={onExport}><Download size={16}/>{t.export}</button></div><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/><div className="table-wrap"><table><thead><tr><th>{t.user}</th><th>{t.projectName}</th><th>{t.projectId}</th><th>{t.date}</th></tr></thead><tbody>{records.map((r:Completion)=><tr key={r.project_id+r.user_id}><td>{r.profiles?.full_name}</td><td>{r.projects?.name}</td><td>{r.projects?.project_code}</td><td>{r.completed_on}</td></tr>)}</tbody></table></div>{!records.length && <div className="empty">{t.noProjects}</div>}</section></> }
function FinishModal({t,project,onClose,onSubmit}: any) { return <div className="modal-backdrop"><form className="modal" onSubmit={onSubmit}><h2>{t.finish}: {project.name}</h2><div className="field"><label>{t.selectDate}</label><input name="completed_on" type="date" min={minDate()} max={today()} defaultValue={today()} required/></div><p className="note">{t.dateNote}</p><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>{t.cancel}</button><button className="primary"><CheckCircle2 size={16}/>{t.save}</button></div></form></div> }
function CreateModal({t,users,onClose,onSubmit}: any) { return <div className="modal-backdrop"><form className="modal" onSubmit={onSubmit}><h2>{t.createProject}</h2><div className="field"><label>{t.projectName}</label><input name="name" required/></div><div className="field"><label>{t.projectId}</label><input name="code" required placeholder="PRJ-001"/></div><div className="field"><label>{t.description}</label><input name="description"/></div><div className="field"><label>{t.assignTo}</label><select name="user_id"><option value="">{t.allUsers}</option>{users.filter((u:Profile)=>u.role==='user').map((u:Profile)=><option value={u.id} key={u.id}>{u.full_name}</option>)}</select></div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>{t.cancel}</button><button className="primary"><Plus size={16}/>{t.create}</button></div></form></div> }
